python code/run_summarization.py \
    --model_name_or_path pretrain_model/bart-base \
    --do_train \
    --do_eval \
    --train_file data/train.json \
    --validation_file data/dev.json \
    --text_column 原文 \
    --summary_column 英文整编 \
    --output_dir ./output \
    --use_fast_tokenizer false \
    --per_device_train_batch_size=4 \
    --per_device_eval_batch_size=4 \
    --evaluation_strategy "steps" \
    --eval_steps 100 \
    --overwrite_output_dir \
    --predict_with_generate
